<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Seed customers for company_id=5, created_by=2.
     * Run: php artisan db:seed --class=CustomerSeeder
     *
     * Requires companies.id=5 and users.id=2 to exist.
     */
    public function run(): void
    {
        $rows = $this->customerRows();

        foreach ($rows as [$name, $state]) {
            Customer::updateOrCreate(
                [
                    'company_id' => 5,
                    'name' => $name,
                ],
                [
                    'created_by' => 2,
                    'state' => $state,
                    'phone' => null,
                    'email' => null,
                    'address' => null,
                    'authorized_person' => null,
                    'contact_details' => '0000000000',
                    'gst_number' => 'N/A',
                    'md_details' => null,
                ]
            );
        }
    }

    /**
     * @return list<array{0: string, 1: string}>
     */
    private function customerRows(): array
    {
        return [
            ['J C BUDHIRAJA HOSIERY', 'Punjab'],
            ['NEVA GARMENTS LTD', 'Punjab'],
            ['AGGARWAL ENTERPRISES', 'Haryana'],
            ['HINGLAJ PROCESSOR', 'Punjab'],
            ['SP INDUSTRIES', 'Punjab'],
            ['AARON FABRICS', 'Punjab'],
            ['AKASH KNITWEARS UNIT 2', 'Punjab'],
            ['JAY BEE WOOLLEN MILLS', 'Punjab'],
            ['LUCKY FABRICS', 'Punjab'],
            ['D R SONS', 'Punjab'],
            ['MAA FABRICS', 'Punjab'],
            ['RSDYEING FINISHING PRIVATE LIMITED', 'Punjab'],
            ['LOTUS CLOTHING CO', 'Punjab'],
            ['CRYSTAL DYEING FINISHING MILLS', 'Punjab'],
            ['HINDUSTAN FASHION', 'Punjab'],
            ['NAVKAR DYEING FINISHING MILLS', 'Punjab'],
            ['SUPERFINE KNITTER LIMITED', 'Punjab'],
            ['SURYA TEXTILE MILLS', 'Punjab'],
            ['S P EXPORTS', 'Punjab'],
            ['RG MERCHANDISER', 'Punjab'],
            ['VARDHMAN JAIN FABRICS', 'Punjab'],
            ['NARESH FABRICS I', 'Punjab'],
            ['SARAL DYERS UNIT I', 'Punjab'],
            ['SANGAT DYEING HOUSE', 'Punjab'],
            ['WOOL WORTH INDIA', 'Punjab'],
            ['AMIT TEXTILES', 'Punjab'],
            ['KHUSHBOO ENTERPRISES', 'Punjab'],
            ['YASH TEXTILE MILL', 'Punjab'],
            ['J J INDUSTRIES', 'Punjab'],
            ['JAWAHAR TEXTILE', 'Punjab'],
            ['SHRI SUDHA FABRICS', 'Punjab'],
            ['S T S KNIT FABRIC', 'Punjab'],
            ['RICKY FABRICS', 'Punjab'],
            ['ZINNY SALES', 'Punjab'],
            ['PURURAJ FABRICS', 'Punjab'],
            ['DENIMOZ INTERNATIONAL PRIVATE LIMITED', 'Punjab'],
            ['MARRINO TEX CRAFT', 'Punjab'],
            ['USABH KNIT FAB', 'Punjab'],
            ['MAKE WAY KNIT FAB', 'Punjab'],
            ['KRISHNA PROCESSORS', 'Punjab'],
            ['SHRI GOPAL JI DYEING HOUSE I UNIT', 'Punjab'],
            ['NITYA FIBRES PRIVATE LIMITED', 'Punjab'],
            ['SUNRISE DYERS PROCESSORS PVT LTD', 'Punjab'],
            ['ADIYOGI CREATIONS', 'Punjab'],
            ['SBC EXPORT LIMITED', 'Uttar Pradesh'],
            ['AGGARWAL CREATIONS', 'Punjab'],
            ['AEIRY KNITWEARS', 'Punjab'],
            ['SHRI RAM KNIT FAB', 'Punjab'],
            ['R S DYEING AND PROCESSING HOUSE', 'Punjab'],
            ['RAJU TEXTILES', 'Punjab'],
            ['NANDANI ENTERPRISES', 'Punjab'],
            ['MISHRA SONS', 'Punjab'],
            ['SKY CLOTHING CO', 'Punjab'],
            ['B L ENTERPRISES', 'Punjab'],
            ['K S TANGRI FINISHING TEXTILE MILLS', 'Punjab'],
            ['JAGDAMBA ENTERPRISES', 'Punjab'],
            ['SAPNA TRADING COMPANY', 'Punjab'],
            ['GS INTERNATIONAL', 'Uttar Pradesh'],
            ['SHREY FABRICS', 'Punjab'],
            ['UPMA KNIT FAB', 'Punjab'],
            ['OCEAN KNIT FAB', 'Punjab'],
            ['ADINATH KNIT', 'Punjab'],
            ['M S AUTO CENTRE', 'West Bengal'],
            ['RAJ SHAWL EMPEROR', 'Punjab'],
            ['ASHIMA KNIT FAB', 'Punjab'],
            ['GRV TEXTILE MILLS', 'Punjab'],
            ['S V B HOSIERY WORKS', 'Punjab'],
            ['V2V EXPORTS INDUSTRIES PRIVATE LIMITED', 'Punjab'],
            ['M S R S GUPTA FABRICS', 'Punjab'],
            ['TRIDEV KNIT FAB', 'Punjab'],
            ['SAGAR UDYOG', 'Punjab'],
            ['OSWAL DYEING AND FINISHING MILLS PVT LTD', 'Punjab'],
            ['L K SPORTS', 'Punjab'],
            ['HIMACHAL WOOLLEN MILLS', 'Punjab'],
            ['INDRA HOSIERY MILLS', 'Punjab'],
            ['V P THAMMAN HOSIERY', 'Punjab'],
            ['LOVELY CHOICE', 'Punjab'],
            ['A G INTERNATIONAL', 'Punjab'],
            ['ADISH FABRICS', 'Punjab'],
            ['SURYA KNITWEAR', 'Punjab'],
            ['OM KNIT FAB', 'Punjab'],
            ['NANDA SPINNING LLP', 'Punjab'],
            ['ANSH PROCESSORS', 'Punjab'],
            ['RAGHAV ENTERPRISES', 'Punjab'],
            ['SHIVAAY FABRICS', 'Punjab'],
            ['KAUSHIK KNITWEARS', 'Punjab'],
            ['JIGYASA KNITWEAR', 'Punjab'],
            ['D G PROCESSORS', 'Punjab'],
            ['KARAN FABRICS', 'Punjab'],
            ['VISHAL ENTERPRISES', 'Punjab'],
            ['TANUJ ENTERPRISES', 'Punjab'],
            ['ADITYA HOSIERY', 'Punjab'],
            ['SAFFRON KNITWEAR', 'Punjab'],
            ['SAKSHI ENTERPRISES', 'Punjab'],
            ['JD APPARELS', 'Punjab'],
            ['MAYANK FABRICS', 'Punjab'],
            ['VALLABH KNITWEARS', 'Punjab'],
            ['RAMA KRISHNA DYEING', 'Punjab'],
            ['ABHINANDAN KNITS PVT LTD', 'Punjab'],
            ['N K KNITS', 'Punjab'],
            ['PANKAJ KNITTING', 'Punjab'],
            ['RAMYA BALAJI ALLOY PVT LTD', 'Punjab'],
            ['VARDHMAN THERMOPACK INDUSTRIES', 'Punjab'],
            ['TANSIA FABRIC', 'Punjab'],
            ['ANIL JAIN GARMENTS', 'Punjab'],
            ['PREMIER FABRICS', 'Punjab'],
            ['D R SYNTHETICS', 'Punjab'],
            ['FAIZAN TRADERS', 'Punjab'],
            ['MEGHA PROCESSORS', 'Punjab'],
            ['TOP MAX', 'Punjab'],
            ['A TO Z GARMENTS', 'Punjab'],
            ['ANANT KNIT FAB', 'Punjab'],
            ['GOVIND KNITWEARS', 'Punjab'],
            ['CUTE STUFF', 'Punjab'],
            ['KHUSHBOO KNITS INDIA', 'Punjab'],
            ['MAYUR KNIT FAB', 'Punjab'],
            ['AADI KNITWEAR', 'Punjab'],
            ['ANVI FABRIC', 'Punjab'],
            ['AIM KNITWEAR', 'Punjab'],
            ['SHIVAAY', 'Punjab'],
            ['SATYAM KNITTING', 'Punjab'],
            ['NAVKAR HOSIERY WOOLLEN MILLS', 'Punjab'],
            ['KAPOOR KNIT', 'Punjab'],
            ['DK DAWAR HOSIERY', 'Punjab'],
            ['SHIV FABRICS', 'Punjab'],
            ['SHIVA PROCESSORS', 'Punjab'],
            ['AMAR JYOT TEXTILE MILLS', 'Punjab'],
            ['RAVI TRADERS', 'Punjab'],
            ['SWASTIK KNIT FAB', 'Punjab'],
            ['SWINI KNITWEARS', 'Punjab'],
            ['SHRAMAN JI FABRICS PVT LTD', 'Punjab'],
            ['AYISHA INDUSTRIES', 'Punjab'],
            ['TEXAS HOSIERY MILLS', 'Punjab'],
            ['SD KNITWEAR', 'Punjab'],
            ['KUSHWAHA FABRIC', 'Punjab'],
            ['TRUSTEX INDUSTRIES', 'Punjab'],
            ['NATO INTERNATIONAL', 'Punjab'],
            ['SATISH INDUSTRIES', 'Punjab'],
            ['ARUSHI KNITWEAR', 'Punjab'],
            ['A P GROVER HOSIERY', 'Punjab'],
            ['OM KNITS', 'Punjab'],
            ['V K FABRICS', 'Punjab'],
            ['S N MIGLANI HOSIERY', 'Punjab'],
            ['RISHI KNIT', 'Punjab'],
            ['RADHE RADHE KNITTERS', 'Punjab'],
            ['EMM SONS KNITWEAR', 'Punjab'],
            ['SERAJ MS KNITTING', 'Punjab'],
        ];
    }
}
